### ISSUE TITLE
老友哒哒 可以添加守护进程的功能吗。服务器经常宕机。

### ISSUE THREAD

**Issue by Goog686ii** [quniu/ssrpanel-deploy#1]
老友哒哒 可以添加守护进程的功能吗。服务器经常宕机。

**Comment by ntgeralt** [comment]
ssrpanel面板一键脚本有些歧义，叫做ssrpanel面板后端一键脚本更恰当

**Comment by quniu** [comment]
> 老友哒哒 可以添加守护进程的功能吗。服务器经常宕机。

不考虑这个
