### ISSUE TITLE
萌新一枚，喜欢鼓捣这些东西，愁没人指导，能不能加个telegram

### ISSUE THREAD

**Issue by donnychenji** [quniu/ssrpanel-deploy#2]
折腾爱好者，不做商业用途，自己鼓捣玩玩v2ray，之前装了胖虎兄弟的ssrpanel，后端节点始终对接不上，用了你的脚本成功对接，想了解一下对接的细节，能不能加个telegram？

**Comment by quniu** [comment]
道路千万条，安全第一条
